server:
  port: 9090
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: service-1
          uri: http://localhost:8080/
          predicates:
            - Path=/service-1/**
        - id: service-2
          uri: http://localhost:8081/
          predicates:
            - Path=/service-2/**
management:
  endpoints:
    web:
      exposure:
        include: "*"




